# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a368117f8b54630daa5bc29557c5596"
name = "GetPawtrait Custom App"
handle = "getpawtrait-custom-app"
application_url = "https://consisting-mother-diet-blocked.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://consisting-mother-diet-blocked.trycloudflare.com/auth/callback",
  "https://consisting-mother-diet-blocked.trycloudflare.com/auth/shopify/callback",
  "https://consisting-mother-diet-blocked.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
