name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "concurrently -k \"npm run extension:watch\" \"npx prisma migrate deploy && npm exec remix vite:dev\""
